// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOcqFhKC0O-Ei-eEHolIMG1ONJotKI8wk',
    appId: '1:227359733617:web:1aae43328cfaf5aab5e8d0',
    messagingSenderId: '227359733617',
    projectId: 'the-outfit-app-cec29',
    authDomain: 'the-outfit-app-cec29.firebaseapp.com',
    storageBucket: 'the-outfit-app-cec29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX7tEY-xd49sASGqOQ0-Y4xyxCJTaeROQ',
    appId: '1:227359733617:android:369443d900a65041b5e8d0',
    messagingSenderId: '227359733617',
    projectId: 'the-outfit-app-cec29',
    storageBucket: 'the-outfit-app-cec29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa8acAjARKTHsDbNXDl7PJ4jbKYcGQijo',
    appId: '1:227359733617:ios:6d074619f1760a2ab5e8d0',
    messagingSenderId: '227359733617',
    projectId: 'the-outfit-app-cec29',
    storageBucket: 'the-outfit-app-cec29.firebasestorage.app',
    iosBundleId: 'com.example.theOutfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa8acAjARKTHsDbNXDl7PJ4jbKYcGQijo',
    appId: '1:227359733617:ios:6d074619f1760a2ab5e8d0',
    messagingSenderId: '227359733617',
    projectId: 'the-outfit-app-cec29',
    storageBucket: 'the-outfit-app-cec29.firebasestorage.app',
    iosBundleId: 'com.example.theOutfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOcqFhKC0O-Ei-eEHolIMG1ONJotKI8wk',
    appId: '1:227359733617:web:86d0fd8422448437b5e8d0',
    messagingSenderId: '227359733617',
    projectId: 'the-outfit-app-cec29',
    authDomain: 'the-outfit-app-cec29.firebaseapp.com',
    storageBucket: 'the-outfit-app-cec29.firebasestorage.app',
  );
}
