// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

import 'providers/cart_provider.dart';
import 'providers/wishlist_provider.dart';
import 'providers/settings_provider.dart';
import 'providers/user_provider.dart';
import 'providers/product_provider.dart';
import 'providers/payment_method_provider.dart';
import 'utils/app_constants.dart';
import 'utils/page_routes.dart';

// Screens
import 'screens/splash_screen.dart';
import 'screens/login_screen.dart';
import 'screens/register_screen.dart';
import 'screens/main_screen.dart';
import 'screens/product_listing_screen.dart';
import 'screens/product_detail_screen.dart';
import 'screens/cart_screen.dart';
import 'screens/wishlist_screen.dart';
import 'screens/checkout_screen.dart';
import 'screens/settings_screen.dart';
import 'screens/search_screen.dart';
import 'screens/orders_screen.dart';
import 'screens/edit_profile_screen.dart';
import 'screens/help_screen.dart';
import 'screens/change_password_screen.dart';
import 'screens/payment_methods_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Initialize Firebase ────────────────────────────────────────────────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor:                    Colors.transparent,
    statusBarIconBrightness:           Brightness.light,
    systemNavigationBarColor:          AppColors.surface,
    systemNavigationBarIconBrightness: Brightness.light,
  ));

  runApp(const TheOutfitApp());
}

class TheOutfitApp extends StatelessWidget {
  const TheOutfitApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // User / Auth — must be first so other providers can read uid
        ChangeNotifierProvider(create: (_) => UserProvider()..init()),

        // Products — starts streaming from Firestore immediately
        ChangeNotifierProvider(create: (_) => ProductProvider()..init()),

        // Cart + Wishlist — initialized after login via ProxyProvider
        ChangeNotifierProxyProvider<UserProvider, CartProvider>(
          create: (_) => CartProvider(),
          update: (_, userProv, cart) {
            if (userProv.isLoggedIn && userProv.uid != null) {
              cart!.init(userProv.uid!);
            } else {
              cart!.clear();
            }
            return cart;
          },
        ),

        ChangeNotifierProxyProvider<UserProvider, WishlistProvider>(
          create: (_) => WishlistProvider(),
          update: (_, userProv, wishlist) {
            if (userProv.isLoggedIn && userProv.uid != null) {
              wishlist!.init(userProv.uid!);
            } else {
              wishlist!.clear();
            }
            return wishlist;
          },
        ),

        ChangeNotifierProvider(create: (_) => SettingsProvider()),
        ChangeNotifierProvider(create: (_) => PaymentMethodProvider()),
      ],
      child: MaterialApp(
        title: 'The Outfit',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.darkTheme,
        initialRoute: AppRoutes.splash,
        onGenerateRoute: (settings) {
          switch (settings.name) {
            case AppRoutes.splash:
              return FadeScaleRoute(page: const SplashScreen(), routeSettings: settings);
            case AppRoutes.login:
              return FadeScaleRoute(page: const LoginScreen(), routeSettings: settings);
            case AppRoutes.register:
              return SlideRightRoute(page: const RegisterScreen(), routeSettings: settings);
            case AppRoutes.main:
            case AppRoutes.home:
            case AppRoutes.profile:
              return FadeScaleRoute(page: const MainScreen(), routeSettings: settings);
            case AppRoutes.cart:
              return SlideUpRoute(page: const CartScreen());
            case AppRoutes.wishlist:
              return SlideRightRoute(page: const WishlistScreen(), routeSettings: settings);
            case AppRoutes.productList:
            case AppRoutes.products:
              return SlideRightRoute(page: const ProductListingScreen(), routeSettings: settings);
            case AppRoutes.productDetail:
              return FadeScaleRoute(page: const ProductDetailScreen(), routeSettings: settings);
            case AppRoutes.checkout:
              return SlideUpRoute(page: const CheckoutScreen());
            case AppRoutes.settings:
              return SlideRightRoute(page: const SettingsScreen(), routeSettings: settings);
            case AppRoutes.search:
              return FadeScaleRoute(page: const SearchScreen(), routeSettings: settings);
            case AppRoutes.orders:
            case AppRoutes.reviews:
              return SlideRightRoute(page: const OrdersScreen(), routeSettings: settings);
            case AppRoutes.editProfile:
              return SlideRightRoute(page: const EditProfileScreen(), routeSettings: settings);
            case AppRoutes.help:
              return SlideRightRoute(page: const HelpScreen(), routeSettings: settings);
            case AppRoutes.changePassword:
              return SlideRightRoute(page: const ChangePasswordScreen(), routeSettings: settings);
            case AppRoutes.paymentMethods:
              return SlideRightRoute(page: const PaymentMethodsScreen(), routeSettings: settings);
            default:
              return FadeScaleRoute(page: const LoginScreen(), routeSettings: settings);
          }
        },
      ),
    );
  }
}
